### ISSUE TITLE
Did you use GPU?

### ISSUE THREAD

**Issue by ssdutHB** [wondervictor/WESPE.pytorch#1]
In your code, I didn't see the processing of input data, so I am wondering if you use GPU to accelerate your computation. And I also want to know that whether the operation of Gaussian blur in scipy will be influenced if we use GPU.

**Comment by wondervictor** [comment]
Sorry about that, I have just finished the basic network, I will rewrite the code and test it soon. :)

**Comment by ssdutHB** [comment]
Thanks for your quick reply. I am now try to applying some scipy operation on the gpu variable tensor whcih is the output from my network. Could you please tell me if I can finish the task as following:
gpu variable tensor -> cpu variable tensor -> cpu numpy array -> cpu numpy array after scipy operation -> cpu variable tensor -> gpu variable tenor. Will the above method work ？

**Comment by RoyiAvital** [comment]
Any progress?

**Comment by wondervictor** [comment]
Now new code has been updated
