### ISSUE TITLE
Is there a runnable code?

### ISSUE THREAD

**Issue by CV-JunchengLi** [wondervictor/WESPE.pytorch#3]
Is there a runnable code?

**Comment by wondervictor** [comment]
I will spare some time to revise the code and update it in the comming week.

**Comment by CV-JunchengLi** [comment]
Looking forward to the runnable code, thank you ~

**Comment by wondervictor** [comment]
code has been update

**Comment by CV-JunchengLi** [comment]
Thank you very much!!!
